[package]
name = "console"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
ppu = { path = "../ppu" }
constants = { path = "../constants" }
paste = "1.0.15"

[features]
debugger = []
