[package]
name = "rgbed"
version = "0.1.0"
edition = "2024"

[dependencies]
text_io = "0.1.13"
console = { path = "../console", features = ["debugger"] }
constants = { path = "../constants" }
log = "0.4.27"
env_logger = "0.11.8"

